excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Lydiaofficial.github.io
title: Rebelzine
tagline: A log of love,dating and friendship tips
description: REBELZINE
paginate: 10